name: github_lookup
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #DI
  get_it: ^7.6.4
  injectable: ^2.3.2

  #STATE_MANAGEMENT
  flutter_bloc: ^8.1.4

  #API
  dio: ^5.4.1
  retrofit: ^4.1.0

  #UTILS
  go_router: ^13.2.0
  equatable: ^2.0.5
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  collection: ^1.17.2

  #VIEW
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  retrofit_generator: ^8.1.0
  injectable_generator: ^2.4.1
  flutter_lints: ^2.0.0
  go_router_builder: ^2.4.1

flutter:
  uses-material-design: true